# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5bb24654f1c7b9b0048c3c8d4f97f9689ad8c44f64b38aa4d18350168cf3937d00dd27e7761bc811080ed0a1d313fa1c02313fc1f866784f4131d170d4dad89

  twitter_api_key:  DwFZ3JFjUvQl4b1oJIQos3ghT
  twitter_api_secret: q6W8qpEDRuOln8GQIfFrtKPWlQw73qbohQl4EBjo6VWHMORa9D
  facebook_api_key: 166971660489416
  facebook_api_secret: 3ae58d60b2d291adfff498899c713923
  vk_api_key: 5963835
  vk_api_secret: BLjdpbQz6JHOFBtYhwH3
  google_api_id: 672137796670-468qgg116ktr5f7dg5n452414edhl2h2.apps.googleusercontent.com
  google_api_key: HEXVW0Us38RwBkv1SF_pp3dN

test:
  secret_key_base: f7e7a7b4c2c5591e67a508f4de26194fafee639a23aa3726aa09a5223ab7876ab007d59202d470f65fcd8e02ee2d0e7488d4dcce992c433cf3e8b3d6fe3e002e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
